function S_combined = get_SensitivityMatrix(in1,in2,in3,Elv,Erv)
%get_SensitivityMatrix
%    S_combined = get_SensitivityMatrix(IN1,IN2,IN3,Elv,Erv)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    10-Jul-2026 20:35:46

Cpa = in2(:,10);
Cpv = in2(:,7);
Csa = in2(:,8);
Csv = in2(:,9);
Raval = in2(:,3);
Rmval = in2(:,2);
Rpul = in2(:,1);
Rpval = in2(:,6);
Rsys = in2(:,4);
Rtval = in2(:,5);
Vlv = in1(2,:);
VlvU = in3(:,2);
Vpa = in1(6,:);
VpaU = in3(:,6);
Vpv = in1(1,:);
VpvU = in3(:,1);
Vrv = in1(5,:);
VrvU = in3(:,5);
Vsa = in1(3,:);
VsaU = in3(:,3);
Vsv = in1(4,:);
VsvU = in3(:,4);
t2 = 1.0./Cpa;
t4 = 1.0./Cpv;
t6 = 1.0./Csa;
t8 = 1.0./Csv;
t10 = 1.0./Raval;
t12 = 1.0./Rmval;
t14 = 1.0./Rpul;
t16 = 1.0./Rpval;
t18 = 1.0./Rsys;
t20 = 1.0./Rtval;
t22 = -VlvU;
t23 = -VpaU;
t24 = -VpvU;
t25 = -VrvU;
t26 = -VsaU;
t27 = -VsvU;
t3 = t2.^2;
t5 = t4.^2;
t7 = t6.^2;
t9 = t8.^2;
t11 = t10.^2;
t13 = t12.^2;
t15 = t14.^2;
t17 = t16.^2;
t19 = t18.^2;
t21 = t20.^2;
t28 = Vlv+t22;
t29 = Vpa+t23;
t30 = Vpv+t24;
t31 = Vrv+t25;
t32 = Vsa+t26;
t33 = Vsv+t27;
t34 = Elv.*t28;
t35 = Erv.*t31;
t36 = t2.*t29;
t37 = t4.*t30;
t38 = t6.*t32;
t39 = t8.*t33;
t40 = t10.*t28;
t41 = t12.*t28;
t42 = t16.*t31;
t43 = t20.*t31;
t52 = t7.*t10.*t32;
t53 = t5.*t12.*t30;
t54 = t3.*t14.*t29;
t55 = t3.*t16.*t29;
t56 = t5.*t14.*t30;
t57 = t7.*t18.*t32;
t58 = t9.*t18.*t33;
t59 = t9.*t20.*t33;
t44 = -t36;
t45 = -t37;
t46 = -t38;
t47 = -t39;
t48 = -t40;
t49 = -t41;
t50 = -t42;
t51 = -t43;
t60 = -t52;
t61 = -t55;
t62 = (t34 < t37);
t63 = (t38 < t34);
t64 = (t36 < t35);
t65 = (t35 < t39);
t66 = t34+t45;
t67 = t34+t46;
t68 = t35+t44;
t69 = t35+t47;
t70 = t36+t45;
t71 = t38+t47;
t72 = t11.*t67;
t73 = t13.*t66;
t74 = t17.*t68;
t75 = t21.*t69;
t76 = t15.*t70;
t77 = t19.*t71;
if ~all(cellfun(@isscalar,{t62}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t62)
    t0 = -t73;
else
    t0 = 0.0;
end
if ~all(cellfun(@isscalar,{t62}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t62)
    t1 = t73;
else
    t1 = 0.0;
end
if ~all(cellfun(@isscalar,{t62,t63}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t62 & t63)
    t2 = t72;
elseif (t62)
    t2 = 0.0;
elseif (t63)
    t2 = t72;
else
    t2 = 0.0;
end
if ~all(cellfun(@isscalar,{t63}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t63)
    t3 = -t72;
else
    t3 = 0.0;
end
if ~all(cellfun(@isscalar,{t65}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t65)
    t4 = -t75;
else
    t4 = 0.0;
end
if ~all(cellfun(@isscalar,{t65}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t65)
    t5 = t75;
else
    t5 = 0.0;
end
if ~all(cellfun(@isscalar,{t64,t65}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t64 & t65)
    t6 = t74;
elseif (t65)
    t6 = 0.0;
elseif (t64)
    t6 = t74;
else
    t6 = 0.0;
end
if ~all(cellfun(@isscalar,{t64}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t64)
    t7 = -t74;
else
    t7 = 0.0;
end
if ~all(cellfun(@isscalar,{t62}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t62)
    t8 = t53+t56;
else
    t8 = t56;
end
if ~all(cellfun(@isscalar,{t62}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t62)
    t9 = -t53;
else
    t9 = 0.0;
end
mt1 = [-t76,0.0,0.0,0.0,0.0,t76,t0,t1,0.0,0.0,0.0,0.0,0.0,t2,t3,0.0,0.0,0.0,0.0,0.0,t77,-t77,0.0,0.0,0.0,0.0,0.0,t4,t5,0.0,0.0,0.0,0.0,0.0,t6,t7,t8,t9,0.0,0.0,0.0,-t56,0.0];
if ~all(cellfun(@isscalar,{t62,t63}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t62 & t63)
    t0 = t60;
elseif (t62)
    t0 = 0.0;
elseif (t63)
    t0 = t60;
else
    t0 = 0.0;
end
if ~all(cellfun(@isscalar,{t63}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t63)
    t1 = t52+t57;
else
    t1 = t57;
end
if ~all(cellfun(@isscalar,{t65}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t65)
    t2 = t58+t59;
else
    t2 = t58;
end
if ~all(cellfun(@isscalar,{t65}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t65)
    t3 = -t59;
else
    t3 = 0.0;
end
if ~all(cellfun(@isscalar,{t64,t65}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t64 & t65)
    t4 = t61;
elseif (t65)
    t4 = 0.0;
elseif (t64)
    t4 = t61;
else
    t4 = 0.0;
end
if ~all(cellfun(@isscalar,{t64}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t64)
    t5 = t54+t55;
else
    t5 = t54;
end
if ~all(cellfun(@isscalar,{t62}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t62)
    t6 = t41;
else
    t6 = 0.0;
end
if ~all(cellfun(@isscalar,{t62,t63}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t62 & t63)
    t7 = t48+t49;
elseif (t62)
    t7 = t49;
elseif (t63)
    t7 = t48;
else
    t7 = 0.0;
end
if ~all(cellfun(@isscalar,{t63}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t63)
    t8 = t40;
else
    t8 = 0.0;
end
if ~all(cellfun(@isscalar,{t65}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t65)
    t9 = t43;
else
    t9 = 0.0;
end
mt2 = [t0,t1,-t57,0.0,0.0,0.0,0.0,-t58,t2,t3,0.0,-t54,0.0,0.0,0.0,t4,t5,t6,t7,t8,0.0,0.0,0.0,0.0,0.0,0.0,t9];
if ~all(cellfun(@isscalar,{t64,t65}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t64 & t65)
    t0 = t50+t51;
elseif (t65)
    t0 = t51;
elseif (t64)
    t0 = t50;
else
    t0 = 0.0;
end
if ~all(cellfun(@isscalar,{t64}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t64)
    t1 = t42;
else
    t1 = 0.0;
end
mt3 = [t0,t1];
S_combined = reshape([mt1,mt2,mt3],6,12);
end
